### ISSUE TITLE
Not collecting some applications

### ISSUE THREAD

**Issue by equivalentideas** [planningalerts-scrapers/boroondara#1]
This scraper seems to be missing applications like this one http://eservices.boroondara.vic.gov.au/EPlanning/Pages/XC.Track/SearchApplication.aspx?id=592462 and this one http://eservices.boroondara.vic.gov.au/EPlanning/Pages/XC.Track/SearchApplication.aspx?id=575869

**Comment by equivalentideas** [comment]
@LoveMyData could you explain how #2 fixed this, and then I'm happy to close it :)

**Comment by LoveMyData** [comment]
I put an extra parameters in the URL

**Comment by equivalentideas** [comment]
> I put an extra parameters in the URL

@LoveMyData do you remember why that fixed the bug?

**Comment by LoveMyData** [comment]
there was two issues here, one is the query string, now added PlnPostPer in the quert string and it is matching what council's web site is on offering.
https://github.com/planningalerts-scrapers/boroondara/blob/80bbd750e777d5c248226265b0348e57b8d56d5f/scraper.rb#L19

second issue is the loop for multiple `Base_Url`, the code only executed the first URL and it work correctly because it has a press button. When it is trying to process the second Url, it doesn't have the `press button` to continue anymore, hence it could not parse correctly and skipped the next loop. I hope this make sense.
https://github.com/planningalerts-scrapers/boroondara/blob/8348cf302b9f093fdfbaf177ca6d18c008230f09/scraper.rb#L43-L46

This is why I think this bug is now fixed.

**Comment by equivalentideas** [comment]
@LoveMyData thanks for all that detail ❤️ sounds good to me.
